name: tap_game_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-233.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #architecture
  get: ^4.3.8

  #countdown
  quiver: ^3.0.1+1

  #widget
  flutter_neumorphic: ^3.2.0

  #preferences
  shared_preferences: ^2.0.8
  enum_to_string: ^2.0.1

  #dialog https://pub.dev/packages/proste_dialog
  proste_dialog: ^2.1.2
  #  image_dialog:
  #    path: /Users/ryutaroiseki/flutter_package/image_dialog

#  #icon
#  flutter_launcher_icons: 0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true

#flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/images/icon.png"